stages:
  - build
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        TAG: project_$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
    - if: '$CI_COMMIT_REF_NAME'
      variables:
        TAG: project_$CI_COMMIT_REF_NAME:latest

dev_static_build:
  stage: build
  variables:
    BRANCH: $CI_COMMIT_REF_NAME
  script:
    - echo $BRANCH
    - echo $TAG
  tags:
    - common-shell
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "test"'
      when: on_success

dev_static_deploy:
  stage: deploy
  variables:
    BRANCH: $CI_COMMIT_REF_NAME
  script:
    - echo $BRANCH
    - echo $TAG
  tags:
    - common-shell
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "test"'
      when: on_success
