include:
  - project: 'lizelong/ci-job'
    ref: main
    file: 'ding_work_notice.yml'

stages:
  - build
  - deploy

cache:
  key: '$CI_COMMIT_SHORT_SHA'
  paths:
    - dist/
    - deploy/

# 请修改一下tag的项目名 替换projectName
variables:
  TAG: harbor.deepwisdomai.com/deepwisdom/projectName_$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        MODE: 'prod'
    - if: '$CI_COMMIT_REF_NAME == "test"'
      variables:
        MODE: 'test'
    - if: '$CI_COMMIT_REF_NAME'
      variables:
        MODE: 'dev'

dev_static_build:
  stage: build
  script:
    - CI=true pnpm i
    - npm run build:$MODE
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
      - deploy/
  tags:
    - common-shell
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^(master|dev|test)$/'
      when: always
    - if: '$CI_COMMIT_REF_NAME =~ /^(feat|feture)-.+$/'
      when: manual
  extends: .ding_work_notice

docker_deploy:
  stage: deploy
  before_script:
    - docker login -u $HARBOR_CCR -p $HARBOR_CCR_PASSWORD harbor.deepwisdomai.com
  script:
    - docker build -t $TAG .
    - docker push $TAG
  when: manual
  tags:
    - common-shell
  only:
    - test
    - dev
    - master
  extends: .ding_work_notice
