// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button'];
    Hello: typeof import('./../components/hello.vue')['default'];
    Icon: typeof import('./../components/Icon.vue')['default'];
    IconLoading: typeof import('@arco-design/web-vue/es/icon')['IconLoading'];
    Logo: typeof import('./../components/Logo.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
